lsi: false
safe: true
use_math: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
 
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
